### ISSUE TITLE
'Dynamic grouping'

### ISSUE THREAD

**Issue by t-silvers** [TileDB-Inc/TileDB-CF-Py#144]
I'm interested in best practices for the situation where there are separate TileDB groups containing N-dim data that overlap in one or more coordinates.

Building off of [this example](https://github.com/TileDB-Inc/TileDB-CF-Py/blob/05cfa3f3526c5c9c29ce8df24294c4b5d0e836c6/examples/xarray_engine/tiledb-xarray-basics.ipynb), consider two data sets, `x_data` in group `group_uri` and `new_data` in `other_group_uri`. These are dense arrays, per this library's requirements. As in the example, `x_data` has coordinates (x, y), while `new_data` has coordinates (x, w).

Are best practices to `tiledb.Group.add` an `x_data` array to each group? I.e., something like
```python
with tiledb.open(f"{group_uri}/x_coord", mode="w") as array:
    array[:] = x_data

with tiledb.Group(group_uri, mode="w") as group:
    group.add(uri="x_coord", name="x", relative=True)

# xr.open_dataset(group_uri, engine="tiledb")

with tiledb.open(f"{other_group_uri}/x_coord", mode="w") as array:
    array[:] = x_data

with tiledb.Group(other_group_uri, mode="w") as group:
    group.add(uri="x_coord", name="x", relative=True)

# xr.open_dataset(other_group_uri, engine="tiledb")
```
and pass each unique URI to `open_dataset()`?

**Comment by jp-dark** [comment]
If I understand correctly, you have two (or more) separate groups and you would like to use the same coordinates for a dimension in both groups?

If so, what you did is a valid way to handle this scenario. Since these are just one-dimensional arrays, there isn't too much cost in duplicating the data.

An alternative solution is to use non-relative URIs to use the same coordinates in multiple groups. You could for example create a group `FullDataset` with 3 subgroups `Dataset1`, `Dataset2`, and `Coordinates`. You can then add coordinate arrays in your coordinate group to `Dataset1` and `Dataset2` using the following:

```python
with tiledb.Group("FullDataset/Dataset1", mode="w") as group1:
    group1.add(uri="FullDataset/Coordinates/x_coord", name="x")
with tiledb.Group("FullDataset/Dataset2", mode="w") as group2:
    group2.add(uri="FullDataset/Coordinates/x_coord", name="x")
```

Hope that helps!
